name: PPLoader
main: org.cyberlis.pyloader.PythonLoader
version: 1.2.2
api-version: 1.15
commands:
  pploader:
    description: Load, unload or reload the specified python plugins.
    usage: |
      /<command> ACTION PYTHON_PLUGIN
      Available actions: load, unload, reload
